### ISSUE TITLE
two factor authentication option

### ISSUE THREAD

**Issue by YesThatAllen** [adamvanlente/ghit-app#4] opened 2014-11-08 23:27 UTC
I'd love to try this, but neither it (nor the official iOS app for that matter) allow me to enter my 2Fa code.

Would love to see that supported so I can try this app.

**Comment by adamvanlente** [comment] 2014-11-08 23:32
Thanks for checking out the app!  Did you try logging in?  It should prompt for 2FA after you enter your initial information (it checks at this stage if 2FA is enabled on your account).  Let me know if that works.

**Comment by YesThatAllen** [comment] 2014-11-08 23:35
Hi Adam!  When I enter my github username, then copy & paste my password from 1Password, the screen on my iPhone 5s running iOS 8.1 (not jailbroken) flashes and presents the login screen again.

Happy to try other tests.

**Comment by adamvanlente** [comment] 2014-11-08 23:37
Thanks!  Will test on my end & report back.

**Comment by adamvanlente** [comment] 2014-11-10 15:55
I am going to close this one, since 2FA is working as expected.  I have also confirmed that other iOS apps (there is no official app) like iOctocat and CodeHub are working with 2FA just fine.  Please, do let me know if you have any additional feedback that can help me replicate what you're seeing.  Also, perhaps test your 1Password login on GitHub.com and confirm the problem is not with the pasted password.  Thanks again for your interest in the app!

**Closed as completed by adamvanlente** 2014-11-10 15:55 UTC

**Comment by YesThatAllen** [comment] 2014-11-10 16:55
Follow up - I manually entered the password from 1Password, and was then prompted for my 2FA code.

Once entered, I was able to use the app as expected. Thanks!

**Comment by adamvanlente** [comment] 2014-11-10 16:56
Great news. Thanks!
